POST http://localhost:3001/api/rounds
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InR1cGVwaXRrIiwiX2lkIjoiNjEzZjQyMTQ1YWNmM2UwMDE2MWQ0NmU2IiwiaWF0IjoxNjMxNjk4NzA5fQ.50JkgWe2tUxuwPDywZB4nIVHtGRwoYtJbxU_uFGPvvw

{
    "score":[],
    "date":"2022-09-14T15:30:25.216+00:00",
    "player":"613f42145acf3e00161d46e6",
    "course":"6139f297d2eaa846d84f2dc4"
}