POST http://localhost:3001/api/courses/ HTTP/1.1
content-type: application/json

{
    "name": "Jyväs-Golf",
    "pars": [
        { "par": 3 },
        { "par": 4 },
        { "par": 4 },
        { "par": 4 },
        { "par": 4 },
        { "par": 3 },
        { "par": 4 },
        { "par": 4 },
        { "par": 5 }
    ]
}


###     

 
POST http://localhost:3001/api/courses/ HTTP/1.1
content-type: application/json

{
        "name": "Muurame Golf",
        "pars": [
            { "par": 5 },
            { "par": 4 },
            { "par": 3 },
            { "par": 4 },
            { "par": 3 },
            { "par": 5 },
            { "par": 4 },
            { "par": 3 },
            { "par": 4 },
            { "par": 4 },
            { "par": 5 },
            { "par": 4 },
            { "par": 3 },
            { "par": 4 },
            { "par": 3 },
            { "par": 5 },
            { "par": 4 },
            { "par": 4 }
        ]
    }

